param(
  [ValidateSet("Local", "Lan")]
  [string]$Mode = "Local",
  [string]$FrontendOrigin,
  [string]$HostName,
  [int]$Port = 8787,
  [string]$ApiKey,
  [string]$OllamaBaseUrl = "http://127.0.0.1:11434",
  [string]$Model = "qwen3:1.7b",
  [string]$A3Model = "qwen3:4b",
  [switch]$Force,
  [switch]$InteractiveHelp
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\common.ps1"

if ($InteractiveHelp) {
  if ($Mode -eq "Lan") {
    Write-Host "Рапорт: настройка общего ИИ-сервиса в сети" -ForegroundColor Cyan
    Write-Host "Этот режим нужен, если одним ИИ-сервисом будут пользоваться несколько человек."
    Write-Host "Пример адреса сайта Рапорта: https://bi.ekb.ru/llmtest/"
    Write-Host "Можно вставить полный адрес страницы. Скрипт сам сохранит только сайт: https://bi.ekb.ru."
    Write-Host ""
  } else {
    Write-Host "Рапорт: настройка ИИ-сервиса на этом компьютере" -ForegroundColor Cyan
    Write-Host "Этот режим подходит, если Рапорт и ИИ-сервис запускаются на одном ПК."
    Write-Host "Будет создан файл backend\raport-llm\.env для http://127.0.0.1:8787."
    Write-Host "Если Рапорт открыт с корпоративного сайта, укажите его адрес, например https://bi.ekb.ru/llmtest/."
    Write-Host ""
  }
}

if ($InteractiveHelp -and -not $FrontendOrigin) {
  $FrontendOrigin = Read-Host "Введите адрес сайта Рапорта"
  if (-not $FrontendOrigin) {
    if ($Mode -eq "Lan") {
      Write-Host "Адрес сайта Рапорта обязателен для сетевого режима." -ForegroundColor Red
      exit 1
    }
    $FrontendOrigin = "http://127.0.0.1:5173"
  }
}

if (-not $FrontendOrigin) {
  $FrontendOrigin = "http://127.0.0.1:5173"
}

try {
  $FrontendOrigin = ConvertTo-RaportFrontendOrigin $FrontendOrigin
} catch {
  Write-Host $_.Exception.Message -ForegroundColor Red
  exit 1
}

$envPath = Get-PrintLlmEnvPath
if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
  Write-Host "Файл настроек уже существует: $envPath" -ForegroundColor Yellow
  Write-Host "Чтобы пересоздать настройки, запустите этот скрипт с параметром -Force."
  Write-Host "Чтобы только добавить новый сайт Рапорта, запустите 05-change-frontend-site.cmd."
  if ($InteractiveHelp) {
    Write-Host ""
    Write-Host "Что делать дальше:"
    Write-Host "Если настройки верные:"
    Write-Host "1. Запустите 02-start.cmd."
    Write-Host ""
    Write-Host "Если нужно пересоздать настройки вручную из PowerShell:"
    Write-Host "1. Откройте PowerShell в папке deploy\raport-llm."
    Write-Host "2. Для локального режима выполните:"
    Write-Host "   .\init-env.ps1 -Mode Local -Force -InteractiveHelp" -ForegroundColor Cyan
    Write-Host "3. Для сетевого режима выполните:"
    Write-Host "   .\init-env.ps1 -Mode Lan -Force -InteractiveHelp" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Если хотите запускать двойным кликом:"
    Write-Host "1. Используйте 01-init-local.cmd для локального режима."
    Write-Host "2. Используйте 01-init-lan.cmd для сетевого режима."
    Write-Host "3. Используйте 05-change-frontend-site.cmd, если поменялся сайт Рапорта."
  }
  exit 0
}

if (-not $HostName) {
  $HostName = if ($Mode -eq "Lan") { "0.0.0.0" } else { "127.0.0.1" }
}

if ($Mode -eq "Lan" -and -not $ApiKey) {
  $ApiKey = ([guid]::NewGuid().ToString("N"))
}

$allowedOrigins = if ($Mode -eq "Lan") {
  Join-PrintLlmAllowedOrigins @($FrontendOrigin)
} else {
  Join-PrintLlmAllowedOrigins @("http://localhost:5173", "http://127.0.0.1:5173", $FrontendOrigin)
}
$ollamaChatUrl = "$($OllamaBaseUrl.TrimEnd('/'))/api/chat"

$content = @"
# Generated by deploy/raport-llm/init-env.ps1 for backend/raport-llm. Do not commit this file.
RAPORT_LLM_ENABLED=true
RAPORT_LLM_HOST=$HostName
RAPORT_LLM_PORT=$Port
RAPORT_LLM_ALLOWED_ORIGINS=$allowedOrigins
RAPORT_LLM_API_KEY=$ApiKey
RAPORT_LLM_REQUEST_BODY_LIMIT_BYTES=1000000
RAPORT_LLM_HTTP_REQUEST_TIMEOUT_MS=300000
RAPORT_LLM_HTTP_HEADERS_TIMEOUT_MS=60000
RAPORT_LLM_HTTP_KEEP_ALIVE_TIMEOUT_MS=5000

OLLAMA_BASE_URL=$OllamaBaseUrl
OLLAMA_CHAT_URL=$ollamaChatUrl
RAPORT_LLM_MODEL=$Model
RAPORT_LLM_A3_MODEL=$A3Model
RAPORT_LLM_TIMEOUT_MS=30000
RAPORT_LLM_BATCH_SIZE=20
RAPORT_LLM_CONCURRENCY=1

RAPORT_LLM_CACHE_ENABLED=true
RAPORT_LLM_CACHE_DB_PATH=
RAPORT_LLM_SQLITE_BUSY_TIMEOUT_MS=5000
RAPORT_LLM_SCHEMA_VERSION=4
"@

Set-Content -LiteralPath $envPath -Value $content -Encoding UTF8
Write-Host "Создан файл настроек: $envPath" -ForegroundColor Green
if ($Mode -eq "Lan") {
  Write-Host "Сохраните API-ключ и укажите его на главной странице Рапорта в настройках ИИ." -ForegroundColor Yellow
  Write-Host "API-ключ: $ApiKey"
}

if ($InteractiveHelp) {
  $backendUrl = if ($Mode -eq "Lan") { "http://<имя-сервера>:$Port" } else { "http://127.0.0.1:$Port" }
  Write-Host ""
  Write-Host "Текущие параметры:" -ForegroundColor Cyan
  Write-Host "- файл настроек: $envPath"
  Write-Host "- адрес ИИ-сервиса для Рапорта: $backendUrl"
  Write-Host "- разрешенный сайт Рапорта: $FrontendOrigin"
  Write-Host "- адрес Ollama: $OllamaBaseUrl"
  Write-Host "- модель для анализа печати: $Model"
  Write-Host "- модель для A3-помощника: $A3Model"
  Write-Host "- размер порции: 20 документов"
  Write-Host "- параллельных запросов к модели: 1"
  Write-Host ""
  Write-Host "Как изменить модель, адрес Ollama или производительность:"
  Write-Host "1. Откройте файл backend\raport-llm\.env."
  Write-Host "2. Измените OLLAMA_BASE_URL, OLLAMA_CHAT_URL, RAPORT_LLM_MODEL, RAPORT_LLM_A3_MODEL, RAPORT_LLM_BATCH_SIZE или RAPORT_LLM_CONCURRENCY."
  Write-Host "3. Перезапустите сервис: 04-stop.cmd, затем 02-start.cmd."
  Write-Host "4. Проверьте состояние: 03-status.cmd."
  Write-Host ""
  Write-Host "Как изменить сайт Рапорта, которому разрешен доступ к ИИ-сервису:"
  Write-Host "1. Запустите 05-change-frontend-site.cmd."
  Write-Host "2. Вставьте адрес сайта, например https://bi.ekb.ru/llmtest/."
  Write-Host "3. Перезапустите сервис: 04-stop.cmd, затем 02-start.cmd."

  Write-Host ""
  Write-Host "Что делать дальше:"
  if ($Mode -eq "Lan") {
    Write-Host "1. Сохраните API-ключ, который показан выше."
    Write-Host "2. Запустите 02-start.cmd на этом сервере или ПК."
    Write-Host "3. Запустите 03-status.cmd и проверьте, что сервис готов."
    Write-Host "4. В Рапорте укажите адрес сервиса, например http://server:8787, и API-ключ."
    Write-Host "5. Если сервис недоступен с других ПК, проверьте Windows Firewall для порта $Port."
  } else {
    Write-Host "1. Запустите 02-start.cmd."
    Write-Host "2. Затем запустите 03-status.cmd и проверьте, что сервис готов."
    Write-Host "3. В Рапорте откройте Настройки и укажите адрес http://127.0.0.1:$Port."
  }
}
