param(
  [ValidateSet("Local", "Lan")]
  [string]$Mode = "Local",
  [string]$FrontendOrigin = "http://127.0.0.1:5173",
  [string]$HostName,
  [int]$Port = 8787,
  [string]$ApiKey,
  [string]$OllamaBaseUrl = "http://127.0.0.1:11434",
  [string]$Model = "qwen3:4b",
  [switch]$Force
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\common.ps1"

$envPath = Get-PrintLlmEnvPath
if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
  Write-Host "Файл настроек уже существует: $envPath" -ForegroundColor Yellow
  Write-Host "Чтобы пересоздать его, добавьте параметр -Force."
  exit 0
}

if (-not $HostName) {
  $HostName = if ($Mode -eq "Lan") { "0.0.0.0" } else { "127.0.0.1" }
}

if ($Mode -eq "Lan" -and -not $ApiKey) {
  $ApiKey = ([guid]::NewGuid().ToString("N"))
}

$allowedOrigins = if ($Mode -eq "Lan") { $FrontendOrigin } else { "http://localhost:5173,http://127.0.0.1:5173,$FrontendOrigin" }
$ollamaChatUrl = "$($OllamaBaseUrl.TrimEnd('/'))/api/chat"

$content = @"
# Generated by deploy/print-llm/init-env.ps1. Do not commit this file.
PRINT_LLM_CLASSIFIER_ENABLED=true
PRINT_LLM_HOST=$HostName
PRINT_LLM_PORT=$Port
PRINT_LLM_ALLOWED_ORIGINS=$allowedOrigins
PRINT_LLM_API_KEY=$ApiKey
PRINT_LLM_REQUEST_BODY_LIMIT_BYTES=1000000
PRINT_LLM_HTTP_REQUEST_TIMEOUT_MS=300000
PRINT_LLM_HTTP_HEADERS_TIMEOUT_MS=60000
PRINT_LLM_HTTP_KEEP_ALIVE_TIMEOUT_MS=5000

OLLAMA_BASE_URL=$OllamaBaseUrl
OLLAMA_CHAT_URL=$ollamaChatUrl
PRINT_LLM_MODEL=$Model
PRINT_LLM_TIMEOUT_MS=30000
PRINT_LLM_BATCH_SIZE=20
PRINT_LLM_CONCURRENCY=1

PRINT_LLM_CACHE_ENABLED=true
PRINT_LLM_CACHE_DB_PATH=
PRINT_LLM_SQLITE_BUSY_TIMEOUT_MS=5000
PRINT_LLM_SCHEMA_VERSION=4
"@

Set-Content -LiteralPath $envPath -Value $content -Encoding UTF8
Write-Host "Создан файл настроек: $envPath" -ForegroundColor Green
if ($Mode -eq "Lan") {
  Write-Host "Сохраните API-ключ и укажите его на главной странице Рапорта в настройках ИИ." -ForegroundColor Yellow
  Write-Host "API-ключ: $ApiKey"
}
